# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\AcmeBundle\:
        resource: '../src/AcmeBundle/*'
        exclude: '../src/AcmeBundle/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\AcmeBundle\Controller\:
        resource: '../src/AcmeBundle/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # security has highest priority, so others, such as the include mixin, can 
    # be wrapped in a security mixin
    acme.test.securitymixin:
         class: App\AcmeBundle\Mixin\SecurityMixin
         arguments:
             - "@security.authorization_checker"
         tags:
             - { name: app.acme.mixin, priority: 100 }
